# Generated by Django 3.2.20 on 2023-08-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logical_replication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletequeue',
            options={'ordering': ['-created_at']},
        ),
    ]
