# Generated by Django 3.2.20 on 2023-07-26 02:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name', models.CharField(max_length=26)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dummy_app.marker')),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dummy_app.outcome')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummy_app.unit'),
        ),
    ]
