# Generated by Django 3.2.20 on 2023-08-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='sub_outcomes',
            field=models.ManyToManyField(blank=True, related_name='parent_results', to='dummy_app.Outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dummy_app.Category'),
        ),
    ]
