[mypy]
python_version = 3.12
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
plugins = mypy_django_plugin.main
disable_error_code = attr-defined, annotation-unchecked

[mypy.plugins.django-stubs]
django_settings_module = "sample_project.settings"

[mypy-*.migrations.*]
ignore_errors = True
